### ISSUE TITLE
i cant get back to the overworld

### ISSUE THREAD

**Issue by supersentai125** [McJtyMods/Ariente#1]
I used the dirty diamond to get to the dimension but now im stuck and i tried everything

**Comment by McJty** [comment]
yes, there is no way yet. You have to make sure you bring something with you to get back. Or you can use a teleport command from cofh

**Comment by supersentai125** [comment]
cofh?

**Comment by McJty** [comment]
https://minecraft.curseforge.com/projects/cofhcore
