### ISSUE TITLE
NoSuchMethodError - Vec3d: Dedicated Server Crash

### ISSUE THREAD

**Issue by CTRiastad** [McJtyMods/Ariente#3]
Server crash after attacking forcefield. Attack was with SlashBlade projectile attack. Restarted server to attempt to test if it occurs with regular attacks as well but the server immediately crashes when trying to log on (with the same error).

ForceFieldTile:214 is: Vec3d entityCenter = entity.getEntityBoundingBox().getCenter();
I'm not familiar with forge mods but I don't see anything that looks out of place. I suspect that this could actually be an issue caused by a different mod (SlashBlade) if the projectile has no bounding box?

Crash info is below.

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.ariente.blocks.defense.ForceFieldTile.lambda$collideWithEntities$0(ForceFieldTile.java:214)
	at net.minecraft.world.chunk.Chunk.func_177430_a(Chunk.java:936)
	at net.minecraft.world.World.func_175647_a(World.java:3080)
	at mcjty.ariente.blocks.defense.ForceFieldTile.collideWithEntities(ForceFieldTile.java:186)
	at mcjty.ariente.blocks.defense.ForceFieldTile.func_73660_a(ForceFieldTile.java:143)

-- Block entity being ticked --
Details:
	Name: ariente:forcefield // mcjty.ariente.blocks.defense.ForceFieldTile
	Block type: ID #3138 (tile.ariente.forcefield // mcjty.lib.builder.GenericBlockBuilder$1 // ariente:forcefield)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-121,102,135), Chunk: (at 7,6,7 in -8,8; contains blocks -128,0,128 to -113,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #3138 (tile.ariente.forcefield // mcjty.lib.builder.GenericBlockBuilder$1 // ariente:forcefield)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

**Comment by McJty** [comment]
Do you have more information? I think the error log should show a more elaborate stacktrace as well. This stacktrace is giving me where it crashes but not why

**Comment by McJty** [comment]
Oh nm. I see what's wrong. I'll fix that in the next version

**Comment by McJty** [comment]
Fixed in next update
