### ISSUE TITLE
ticking block entity crash

### ISSUE THREAD

**Issue by ewsmith** [McJtyMods/Ariente#7]
https://pastebin.com/s8QEF1eT

**Comment by McJty** [comment]
More information please. How did this happen? Is this a one-time occurance or does it crash all the time?

**Comment by ewsmith** [comment]
it happens any time i enter the ariente dimension.
EDIT: loading after the crash will crash again if im still in the dimension.

**Comment by McJty** [comment]
I will fix this

**Comment by ewsmith** [comment]
https://pastebin.com/7FLdQzYk
now for the levitator

progress! \o/

EDIT: seems to only occur with world gen ones

**Comment by McJty** [comment]
Latest release should fix this
