### ISSUE TITLE
hologui crash on entering ariente dimension via warper

### ISSUE THREAD

**Issue by hanleybrand** [McJtyMods/Ariente#8]
Not much else to say - I downloaded ariente & arienteworld 0.0.22-alphas, theoneprobe 1.4.28, mcjtylib_ng 3.5.2 and hologui 0.0.8-beta to try out ariente -- I grabbed a warper via JEI to check out the custom dimension, but I crashed while it was loading. 

I removed all the mods except for yours to troubleshoot, but still the issue remains (same error). 

Is it possible I have the wrong version of mcjtylib_ng?

---- Minecraft Crash Report ----
// You're mean.

Time: 5/16/19 2:08 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at mcjty.hologui.gui.components.HoloText.render(HoloText.java:56)
	at mcjty.hologui.gui.components.HoloPanel.render(HoloPanel.java:30)
	at mcjty.hologui.gui.HoloGuiEntityRender.doActualRender(HoloGuiEntityRender.java:113)
	at mcjty.hologui.gui.HoloGuiEntityRender.doRender(HoloGuiEntityRender.java:50)
	at mcjty.hologui.gui.HoloGuiEntityRender.func_76986_a(HoloGuiEntityRender.java:20)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mcjty.hologui.gui.components.HoloText.render(HoloText.java:56)
	at mcjty.hologui.gui.components.HoloPanel.render(HoloPanel.java:30)
	at mcjty.hologui.gui.HoloGuiEntityRender.doActualRender(HoloGuiEntityRender.java:113)
	at mcjty.hologui.gui.HoloGuiEntityRender.doRender(HoloGuiEntityRender.java:50)
	at mcjty.hologui.gui.HoloGuiEntityRender.func_76986_a(HoloGuiEntityRender.java:20)

-- Entity being rendered --
Details:
	Entity Type: hologui:hologui_hologui (mcjty.hologui.gui.HoloGuiEntity)
	Entity ID: 198
	Entity Name: Holo GUI
	Entity's Exact location: -4.34, 65.12, 253.89
	Entity's Block location: World: (-5,65,253), Chunk: (at 11,4,13 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: mcjty.hologui.gui.HoloGuiEntityRender@7bc488b7
	Location: 0.87,1.12,0.49 - World: (0,1,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -60.46875
	Delta: 0.42000198
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['hanleybrand'/379, l='MpServer', x=-5.21, y=64.00, z=253.40]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-4,64,244), Chunk: (at 12,4,4 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4821 game time, 4821 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 146 total; [EntityItem['item.item.seeds'/256, l='MpServer', x=44.57, y=63.00, z=259.57], EntityItem['item.item.seeds'/257, l='MpServer', x=43.48, y=63.00, z=259.70], EntityBat['Bat'/258, l='MpServer', x=42.51, y=34.10, z=281.25], EntitySheep['Sheep'/259, l='MpServer', x=43.50, y=63.00, z=303.50], EntitySheep['Sheep'/260, l='MpServer', x=40.54, y=63.00, z=305.16], EntityRabbit['Rabbit'/261, l='MpServer', x=37.67, y=64.00, z=292.67], EntityRabbit['Rabbit'/262, l='MpServer', x=40.50, y=64.00, z=296.50], EntityCreeper['Creeper'/263, l='MpServer', x=41.79, y=28.00, z=318.51], EntitySkeleton['Skeleton'/264, l='MpServer', x=33.50, y=25.00, z=318.50], EntitySheep['Sheep'/265, l='MpServer', x=41.47, y=63.00, z=305.51], EntitySheep['Sheep'/266, l='MpServer', x=40.45, y=63.00, z=306.13], EntityItem['item.tile.flower2.poppy'/267, l='MpServer', x=32.88, y=57.00, z=307.59], EntityItem['item.tile.flower2.allium'/268, l='MpServer', x=32.44, y=48.00, z=314.17], EntityItem['item.tile.flower2.poppy'/269, l='MpServer', x=33.76, y=48.00, z=314.20], EntityItem['item.tile.doublePlant.syringa'/270, l='MpServer', x=45.33, y=63.00, z=316.18], EntityBat['Bat'/277, l='MpServer', x=54.44, y=55.11, z=196.48], EntityItem['item.tile.torch'/278, l='MpServer', x=51.88, y=21.00, z=247.43], EntitySheep['Sheep'/279, l='MpServer', x=59.22, y=64.00, z=254.18], EntitySheep['Sheep'/280, l='MpServer', x=58.50, y=64.00, z=250.50], EntitySheep['Sheep'/281, l='MpServer', x=60.29, y=64.00, z=254.72], EntitySheep['Sheep'/282, l='MpServer', x=58.50, y=64.00, z=251.50], EntitySheep['Sheep'/283, l='MpServer', x=48.09, y=63.00, z=263.75], EntityCreeper['Creeper'/284, l='MpServer', x=60.50, y=31.00, z=279.50], EntitySpider['Spider'/285, l='MpServer', x=58.77, y=31.00, z=281.70], EntitySkeleton['Skeleton'/286, l='MpServer', x=61.53, y=31.00, z=279.72], EntityBat['Bat'/287, l='MpServer', x=63.32, y=31.51, z=280.98], EntityBat['Bat'/288, l='MpServer', x=56.12, y=34.71, z=280.95], EntityItem['item.item.seeds'/289, l='MpServer', x=56.79, y=59.00, z=281.79], EntityItem['item.item.seeds'/290, l='MpServer', x=53.13, y=59.00, z=284.88], EntityItem['item.item.seeds'/291, l='MpServer', x=55.76, y=63.00, z=286.92], EntityItem['item.item.seeds'/292, l='MpServer', x=52.77, y=64.00, z=285.31], EntityItem['item.tile.gravel'/295, l='MpServer', x=56.25, y=20.00, z=294.13], EntityItem['item.tile.gravel'/296, l='MpServer', x=57.61, y=20.00, z=294.88], EntityItem['item.tile.flower2.tulipOrange'/298, l='MpServer', x=52.88, y=32.00, z=309.88], EntitySkeleton['Skeleton'/299, l='MpServer', x=62.50, y=23.00, z=323.18], EntitySkeleton['Skeleton'/300, l='MpServer', x=62.50, y=23.00, z=323.92], EntitySkeleton['Skeleton'/301, l='MpServer', x=57.77, y=23.00, z=323.54], EntitySkeleton['Skeleton'/302, l='MpServer', x=62.50, y=23.00, z=329.50], EntityBat['Bat'/329, l='MpServer', x=64.25, y=27.10, z=329.34], EntityCreeper['Creeper'/330, l='MpServer', x=64.99, y=24.00, z=327.35], EntitySheep['Sheep'/75, l='MpServer', x=-82.59, y=66.25, z=208.60], EntityWitch['Witch'/84, l='MpServer', x=-85.43, y=23.00, z=297.53], EntityZombie['Zombie'/86, l='MpServer', x=-82.50, y=40.00, z=291.50], EntityBat['Bat'/87, l='MpServer', x=-85.67, y=42.00, z=289.08], EntityCow['Cow'/100, l='MpServer', x=-65.50, y=70.00, z=174.50], EntitySkeleton['Skeleton'/104, l='MpServer', x=-68.50, y=44.00, z=176.50], EntityZombie['Zombie'/105, l='MpServer', x=-73.50, y=46.00, z=181.50], EntitySheep['Sheep'/106, l='MpServer', x=-67.59, y=68.00, z=190.55], EntitySheep['Sheep'/107, l='MpServer', x=-69.74, y=68.00, z=189.42], EntityChicken['Chicken'/108, l='MpServer', x=-76.48, y=68.00, z=189.76], EntityChicken['Chicken'/109, l='MpServer', x=-73.38, y=69.00, z=199.02], EntityChicken['Chicken'/110, l='MpServer', x=-66.50, y=69.00, z=194.50], EntityChicken['Chicken'/111, l='MpServer', x=-67.30, y=69.00, z=193.10], EntitySheep['Sheep'/112, l='MpServer', x=-79.24, y=68.00, z=195.45], EntityZombie['Zombie'/114, l='MpServer', x=-78.51, y=48.00, z=217.80], EntitySkeleton['Skeleton'/115, l='MpServer', x=-79.50, y=35.00, z=240.50], EntityZombie['Zombie'/116, l='MpServer', x=-75.50, y=16.00, z=280.50], EntityItem['item.tile.gravel'/117, l='MpServer', x=-66.50, y=36.00, z=286.34], EntityItem['item.tile.gravel'/118, l='MpServer', x=-65.80, y=32.00, z=287.54], EntityItem['item.tile.gravel'/119, l='MpServer', x=-67.93, y=32.00, z=287.52], EntityCreeper['Creeper'/120, l='MpServer', x=-64.50, y=34.00, z=272.50], EntityItem['item.tile.torch'/121, l='MpServer', x=-65.22, y=25.00, z=303.87], EntityEnderman['Enderman'/122, l='MpServer', x=-64.50, y=22.00, z=289.50], EntityCreeper['Creeper'/123, l='MpServer', x=-68.82, y=32.00, z=288.55], EntityPlayerSP['hanleybrand'/379, l='MpServer', x=-5.21, y=64.00, z=253.40], EntityBat['Bat'/124, l='MpServer', x=-70.25, y=34.68, z=295.73], EntityCreeper['Creeper'/125, l='MpServer', x=-79.50, y=29.00, z=314.50], EntityMinecartChest['Minecart with Chest'/126, l='MpServer', x=-75.50, y=28.06, z=327.50], EntitySheep['Sheep'/136, l='MpServer', x=-59.77, y=69.00, z=190.49], EntityMinecartChest['Minecart with Chest'/137, l='MpServer', x=-61.50, y=34.06, z=255.50], EntityMinecartChest['Minecart with Chest'/138, l='MpServer', x=-57.50, y=22.06, z=277.50], EntityBat['Bat'/139, l='MpServer', x=-58.00, y=22.16, z=283.49], EntityItem['item.tile.gravel'/140, l='MpServer', x=-63.88, y=32.00, z=287.59], EntitySkeleton['Skeleton'/141, l='MpServer', x=-51.50, y=32.00, z=278.50], EntityItem['item.tile.torch'/142, l='MpServer', x=-58.64, y=21.00, z=296.59], EntityItem['item.tile.gravel'/143, l='MpServer', x=-60.49, y=25.00, z=302.67], EntityItem['item.tile.gravel'/144, l='MpServer', x=-59.22, y=25.00, z=302.65], EntityItem['item.tile.gravel'/145, l='MpServer', x=-61.80, y=25.00, z=302.88], EntityItem['item.tile.gravel'/146, l='MpServer', x=-61.48, y=25.00, z=302.13], EntityItem['item.tile.gravel'/147, l='MpServer', x=-63.12, y=25.00, z=302.13], EntitySpider['Spider'/148, l='MpServer', x=-52.50, y=31.00, z=299.50], EntityItem['item.tile.torch'/149, l='MpServer', x=-52.13, y=35.00, z=298.33], EntityBat['Bat'/150, l='MpServer', x=-53.75, y=33.10, z=298.52], EntityEnderman['Enderman'/151, l='MpServer', x=-52.50, y=32.00, z=288.50], EntityEnderman['Enderman'/152, l='MpServer', x=-52.50, y=32.00, z=289.50], EntityZombie['Zombie'/153, l='MpServer', x=-54.75, y=49.00, z=302.52], EntityItem['item.tile.gravel'/154, l='MpServer', x=-58.88, y=26.00, z=304.88], EntityCreeper['Creeper'/156, l='MpServer', x=-59.50, y=30.00, z=325.50], EntitySkeleton['Skeleton'/157, l='MpServer', x=-62.50, y=30.00, z=326.50], EntityBat['Bat'/158, l='MpServer', x=-50.25, y=43.10, z=329.75], EntityBat['Bat'/159, l='MpServer', x=-50.73, y=41.18, z=329.30], EntityCreeper['Creeper'/167, l='MpServer', x=-33.55, y=43.00, z=177.45], EntitySkeleton['Skeleton'/168, l='MpServer', x=-37.50, y=32.00, z=179.50], EntityItem['item.tile.flower2.poppy'/169, l='MpServer', x=-36.30, y=63.00, z=199.86], EntityItem['item.tile.flower2.poppy'/170, l='MpServer', x=-37.77, y=63.00, z=199.85], EntityDonkey['Donkey'/171, l='MpServer', x=-43.97, y=63.00, z=267.02], EntityDonkey['Donkey'/172, l='MpServer', x=-43.50, y=63.00, z=269.09], EntityDonkey['Donkey'/173, l='MpServer', x=-47.50, y=63.00, z=271.50], EntityItem['item.tile.torch'/174, l='MpServer', x=-44.88, y=35.00, z=286.16], EntityCreeper['Creeper'/175, l='MpServer', x=-32.50, y=27.00, z=308.50], EntityBat['Bat'/176, l='MpServer', x=-37.00, y=46.17, z=313.80], EntityCreeper['Creeper'/186, l='MpServer', x=-31.50, y=43.00, z=177.50], EntitySheep['Sheep'/187, l='MpServer', x=-16.84, y=75.00, z=216.37], EntitySheep['Sheep'/188, l='MpServer', x=-26.20, y=70.00, z=223.48], EntityItem['item.item.seeds'/189, l='MpServer', x=-18.47, y=63.00, z=285.22], EntityZombie['Zombie'/190, l='MpServer', x=-23.50, y=29.00, z=298.50], EntitySkeleton['Skeleton'/191, l='MpServer', x=-24.50, y=29.00, z=297.50], EntityItem['item.item.seeds'/192, l='MpServer', x=-28.50, y=63.00, z=299.52], EntityBat['Bat'/193, l='MpServer', x=-21.01, y=43.35, z=319.06], EntitySheep['Sheep'/196, l='MpServer', x=-6.14, y=77.00, z=212.28], EntitySheep['Sheep'/197, l='MpServer', x=-5.97, y=77.00, z=213.24], HoloGuiEntity['Holo GUI'/198, l='MpServer', x=-4.34, y=65.12, z=253.89], EntityZombie['Zombie'/199, l='MpServer', x=-9.31, y=34.00, z=276.77], EntityItem['item.item.seeds'/200, l='MpServer', x=-15.55, y=63.00, z=283.55], EntityItem['item.item.seeds'/201, l='MpServer', x=-15.22, y=63.00, z=286.24], EntityChicken['Chicken'/203, l='MpServer', x=14.50, y=63.00, z=297.50], EntityItem['item.item.seeds'/206, l='MpServer', x=20.70, y=63.00, z=207.88], EntitySquid['Squid'/207, l='MpServer', x=20.67, y=60.00, z=203.60], EntitySquid['Squid'/208, l='MpServer', x=21.64, y=60.23, z=197.53], EntityItem['item.item.seeds'/209, l='MpServer', x=26.24, y=62.00, z=209.48], EntityItem['item.item.seeds'/210, l='MpServer', x=25.94, y=64.00, z=211.90], EntitySheep['Sheep'/211, l='MpServer', x=24.41, y=66.00, z=225.79], EntitySheep['Sheep'/212, l='MpServer', x=25.51, y=65.00, z=237.79], EntitySheep['Sheep'/213, l='MpServer', x=27.34, y=64.00, z=251.48], EntitySheep['Sheep'/214, l='MpServer', x=27.58, y=64.00, z=243.58], EntitySheep['Sheep'/215, l='MpServer', x=21.44, y=62.35, z=259.45], EntitySheep['Sheep'/216, l='MpServer', x=26.60, y=65.00, z=264.22], EntitySheep['Sheep'/217, l='MpServer', x=16.63, y=64.00, z=277.19], EntityCreeper['Creeper'/218, l='MpServer', x=17.63, y=33.00, z=288.94], EntitySkeleton['Skeleton'/219, l='MpServer', x=31.43, y=54.00, z=292.29], EntitySkeleton['Skeleton'/220, l='MpServer', x=27.50, y=31.00, z=317.50], EntityItem['item.tile.sand.default'/221, l='MpServer', x=27.13, y=57.00, z=306.15], EntityItem['item.tile.sand.default'/222, l='MpServer', x=30.88, y=57.00, z=305.29], EntityItem['item.tile.sand.default'/223, l='MpServer', x=27.88, y=57.00, z=306.88], EntityItem['item.tile.sand.default'/224, l='MpServer', x=29.88, y=57.00, z=306.74], EntityItem['item.tile.flower2.tulipRed'/225, l='MpServer', x=27.88, y=57.00, z=306.19], EntityItem['item.tile.flower2.allium'/226, l='MpServer', x=27.17, y=57.00, z=306.78], EntityItem['item.tile.flower2.allium'/227, l='MpServer', x=30.88, y=57.00, z=305.65], EntityItem['item.tile.flower2.houstonia'/228, l='MpServer', x=29.13, y=57.00, z=306.42], EntityItem['item.tile.flower2.allium'/229, l='MpServer', x=31.08, y=48.00, z=314.18], EntityItem['item.tile.flower2.allium'/230, l='MpServer', x=25.39, y=50.00, z=313.30], EntityItem['item.tile.flower2.poppy'/231, l='MpServer', x=27.74, y=49.00, z=314.22], EntitySheep['Sheep'/252, l='MpServer', x=33.13, y=65.00, z=242.74], EntitySheep['Sheep'/253, l='MpServer', x=40.77, y=63.00, z=257.74], EntitySheep['Sheep'/254, l='MpServer', x=43.68, y=63.00, z=258.39], EntitySheep['Sheep'/255, l='MpServer', x=43.49, y=63.00, z=257.30]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.2
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 813150424 bytes (775 MB) / 1309147136 bytes (1248 MB) up to 7158628352 bytes (6827 MB)
	JVM Flags: 3 total; -Xmx7680m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State  | ID           | Version      | Source                             | Signature                                |
|:------ |:------------ |:------------ |:---------------------------------- |:---------------------------------------- |
| LCHIJA | minecraft    | 1.12.2       | minecraft.jar                      | None                                     |
| LCHIJA | mcp          | 9.42         | minecraft.jar                      | None                                     |
| LCHIJA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | forge        | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | mcjtylib_ng  | 3.5.2        | mcjtylib-1.12-3.5.2.jar            | None                                     |
| LCHIJA | hologui      | 0.0.8-beta   | hologui-1.12-0.0.8-beta.jar        | None                                     |
| LCHIJA | ariente      | 0.0.22-alpha | ariente-1.12-0.0.22-alpha.jar      | None                                     |
| LCHIJA | arienteworld | 0.0.22-alpha | arienteworld-1.12-0.0.22-alpha.jar | None                                     |
| LCHIJA | theoneprobe  | 1.4.28       | theoneprobe-1.12-1.4.28.jar        | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-2.4.9' Renderer: 'AMD Radeon Pro 560 OpenGL Engine'
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.2
	OpenGL: AMD Radeon Pro 560 OpenGL Engine GL version 2.1 ATI-2.4.9, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz

**Comment by McJty** [comment]
I know. Already fixed. Will release fix tomorrow

**Comment by hanleybrand** [comment]
oh cool - as a followup I made a new game and used pearls to find a warper, and that one worked fine. 

Mod looks cool!
